# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Authenticate with Google Cloud
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_PROD }}'

       # Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2     
      # Upload app build to GCS bucket
      - name: Deploy app build to GCS bucket
        run: gsutil cp -r *.js gs://checkoutscript.wafi.cash/
      - name:  Invalidate GCP CDN
        run:   gcloud compute url-maps invalidate-cdn-cache cdn-url-map-production --async  --host  checkoutscript.wafi.cash --path "/*"         
